# Generated by Django 5.2.15 on 2026-08-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0015_alter_answer_id_alter_category_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('in', 'answer is one of choices'), ('eq', '=='), ('ne', '!='), ('lt', '<'), ('le', '<='), ('gt', '>'), ('ge', '>=')], default='in', max_length=2)),
                ('choices', models.TextField(blank=True, help_text="Comma-separated parent choice labels, used with the 'in' operator.")),
                ('number', models.FloatField(blank=True, help_text='Used with the numeric operators.', null=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_conditions', to='survey.question')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension_condition', to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_option', models.BooleanField(default=False)),
                ('other_label', models.CharField(default='Other, please specify', max_length=200)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension_extra', to='survey.question')),
            ],
        ),
    ]
