# Generated by Django 5.2 on 2026-06-10 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(limit_choices_to={'user_type': 'participant'}, on_delete=django.db.models.deletion.CASCADE, related_name='protected_identifiers', to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'value')},
            },
        ),
    ]
