# Generated by Django 5.2.15 on 2026-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_protectedidentifier_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax ID collected for remuneration.', max_length=100),
        ),
    ]
