# Generated by Django 4.2 on 2026-05-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0027_remove_googleportabilitydatasource_data_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_sources.datasource')),
            ],
            options={
                'verbose_name': 'Survey Data Source',
                'verbose_name_plural': 'Survey Data Sources',
            },
            bases=('data_sources.datasource',),
        ),
    ]
