# Generated by Django 5.2 on 2026-05-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0027_remove_googleportabilitydatasource_data_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awaredatasource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='googleportabilitydatasource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jsonurldatasource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiktokportabilitydatasource',
            options={},
        ),
    ]
