# Generated by Django 5.2 on 2026-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0028_alter_awaredatasource_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleportabilitydatasource',
            name='data_type_status',
        ),
        migrations.AlterField(
            model_name='googleportabilitydatasource',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized, waiting for data'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='pending', max_length=20),
        ),
    ]
