# Generated by Django 5.2 on 2026-06-01 09:49

import django.db.models.deletion
from django.db import migrations, models


def copy_data_to_niimport(apps, schema_editor):
    """Copy rows from google/tiktok portability tables into the new niimport table."""
    db = schema_editor.connection.alias
    NiimportDataSource = apps.get_model('data_sources', 'NiimportDataSource')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    niimport_ct = ContentType.objects.get_for_model(NiimportDataSource)

    with schema_editor.connection.cursor() as cursor:
        # Copy Google Portability rows
        cursor.execute("""
            INSERT INTO data_sources_niimportdatasource
                (datasource_ptr_id, niimport_source_type, donation_id,
                 donation_token, processing_status, processing_log)
            SELECT datasource_ptr_id, 'google_portability', donation_id,
                   donation_token, processing_status, processing_log
            FROM data_sources_googleportabilitydatasource
        """)

        # Copy TikTok Portability rows
        cursor.execute("""
            INSERT INTO data_sources_niimportdatasource
                (datasource_ptr_id, niimport_source_type, donation_id,
                 donation_token, processing_status, processing_log)
            SELECT datasource_ptr_id, 'tiktok_portability', donation_id,
                   donation_token, processing_status, processing_log
            FROM data_sources_tiktokportabilitydatasource
        """)

        # Update polymorphic content type to point to NiimportDataSource
        cursor.execute("""
            UPDATE data_sources_datasource
            SET polymorphic_ctype_id = %s
            WHERE id IN (
                SELECT datasource_ptr_id FROM data_sources_niimportdatasource
            )
        """, [niimport_ct.pk])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('data_sources', '0029_consolidate_niimport'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiimportDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_sources.datasource')),
                ('niimport_source_type', models.CharField(choices=[('google_portability', 'Google Portability'), ('tiktok_portability', 'TikTok Portability'), ('tiktok_export', 'TikTok Export')], max_length=30)),
                ('donation_id', models.IntegerField(blank=True, null=True)),
                ('donation_token', models.UUIDField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized, waiting for data'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='pending', max_length=20)),
                ('processing_log', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('data_sources.datasource',),
        ),
        migrations.RunPython(copy_data_to_niimport, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tiktokportabilitydatasource',
            name='datasource_ptr',
        ),
        migrations.DeleteModel(
            name='GooglePortabilityDataSource',
        ),
        migrations.DeleteModel(
            name='TikTokPortabilityDataSource',
        ),
        migrations.CreateModel(
            name='GooglePortabilityDataSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_sources.niimportdatasource',),
        ),
        migrations.CreateModel(
            name='TikTokPortabilityDataSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_sources.niimportdatasource',),
        ),
    ]
