# Generated by Django 5.2 on 2026-06-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0030_consolidate_niimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GooglePortabilityDataSource',
        ),
        migrations.DeleteModel(
            name='TikTokPortabilityDataSource',
        ),
    ]
