# Generated by Django 5.2 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0031_delete_googleportabilitydatasource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
