# Generated by Django 5.2.15 on 2026-06-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0032_niimport_donation_config_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletableWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=255)),
                ('downloaded_through', models.DateTimeField(blank=True, help_text='Max row timestamp served to researchers so far.', null=True)),
                ('deletable_through', models.DateTimeField(blank=True, help_text='Set when a researcher marks data up to this point as deletable.', null=True)),
                ('deleted_through', models.DateTimeField(blank=True, help_text='Stamped when the source confirms the purge up to this point.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermarks', to='data_sources.datasource')),
            ],
            options={
                'indexes': [models.Index(fields=['data_type'], name='data_source_data_ty_caab55_idx')],
                'unique_together': {('data_source', 'data_type')},
            },
        ),
    ]
