# Generated by Django 5.2.15 on 2026-06-22 10:58

from django.db import migrations, models


_COLUMNS = ("deletable_through", "deleted_through", "downloaded_through")


# Postgres cannot implicitly cast timestamptz -> bigint, so each column is
# altered with an explicit USING clause converting to Unix time in milliseconds.
# The DDL is Postgres-only; on other backends (SQLite dev databases) it is
# skipped and the state_operations alone keep Django's model state in sync.
def _alter_to_bigint_ms(column):
    return (
        f'ALTER TABLE "data_sources_deletablewatermark" '
        f'ALTER COLUMN "{column}" TYPE bigint '
        f'USING (EXTRACT(EPOCH FROM "{column}") * 1000)::bigint;'
    )


def _alter_to_timestamptz(column):
    return (
        f'ALTER TABLE "data_sources_deletablewatermark" '
        f'ALTER COLUMN "{column}" TYPE timestamptz '
        f'USING to_timestamp("{column}" / 1000.0);'
    )


def _forwards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for column in _COLUMNS:
        schema_editor.execute(_alter_to_bigint_ms(column))


def _backwards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for column in _COLUMNS:
        schema_editor.execute(_alter_to_timestamptz(column))


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0033_deletablewatermark'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_forwards, _backwards),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='deletablewatermark',
                    name='deletable_through',
                    field=models.BigIntegerField(blank=True, help_text='Unix time in milliseconds up to which a researcher has marked data deletable.', null=True),
                ),
                migrations.AlterField(
                    model_name='deletablewatermark',
                    name='deleted_through',
                    field=models.BigIntegerField(blank=True, help_text='Unix time in milliseconds up to which the source confirms data has been purged.', null=True),
                ),
                migrations.AlterField(
                    model_name='deletablewatermark',
                    name='downloaded_through',
                    field=models.BigIntegerField(blank=True, help_text='Max row timestamp (Unix time in milliseconds) served to researchers so far.', null=True),
                ),
            ],
        ),
    ]
