# Generated by Django 5.2.15 on 2026-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0033_deletablewatermark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletablewatermark',
            name='deletable_through',
            field=models.BigIntegerField(blank=True, help_text='Unix time in milliseconds up to which a researcher has marked data deletable.', null=True),
        ),
        migrations.AlterField(
            model_name='deletablewatermark',
            name='deleted_through',
            field=models.BigIntegerField(blank=True, help_text='Unix time in milliseconds up to which the source confirms data has been purged.', null=True),
        ),
        migrations.AlterField(
            model_name='deletablewatermark',
            name='downloaded_through',
            field=models.BigIntegerField(blank=True, help_text='Max row timestamp (Unix time in milliseconds) served to researchers so far.', null=True),
        ),
    ]
