# Generated by Django 5.2.15 on 2026-07-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0034_alter_deletablewatermark_deletable_through_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='device_id',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
