# Generated by Django 4.2 on 2026-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0023_remove_data_source_list_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='source_configurations',
            field=models.JSONField(blank=True, default=dict, help_text='Dict mapping source type names to their configuration. Each entry should have at minimum a \'status\' key (\'required\' or \'optional\'). Optional keys: \'data_start\', \'data_end\' (ISO datetime strings), \'config_file\', \'requested_data_types\' (list of strings, for portability sources). Example: {"AwareDataSource": {"status": "required", "data_start": "2024-01-01T00:00:00"}}'),
        ),
    ]
