# Generated by Django 4.2 on 2026-05-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0024_alter_study_source_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySourceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional')], default='optional', max_length=20)),
                ('requested_data_types', models.TextField(blank=True, default='', help_text='Comma-separated list of data types to request from this source')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_config_entries', to='studies.study')),
            ],
            options={
                'verbose_name': 'Source Configuration',
                'verbose_name_plural': 'Source Configurations',
                'unique_together': {('study', 'source_type')},
            },
        ),
    ]
