# Generated by Django 5.2 on 2026-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0025_studysourceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysourceconfiguration',
            name='config_file',
            field=models.CharField(blank=True, default='', help_text='Optional config file name in the repository for this source (e.g. aware_config.yaml)', max_length=200),
        ),
        migrations.AddField(
            model_name='studysourceconfiguration',
            name='data_end',
            field=models.DateTimeField(blank=True, help_text='End of the data collection period. May be null for ongoing collection.', null=True),
        ),
        migrations.AddField(
            model_name='studysourceconfiguration',
            name='data_start',
            field=models.DateTimeField(blank=True, help_text='Start of the data collection period. May predate consent_date.', null=True),
        ),
    ]
