# Generated by Django 5.2 on 2026-05-29 10:57

from django.db import migrations
from django.utils import timezone
from datetime import datetime


def _parse_dt(value):
    if not value:
        return None
    try:
        dt = datetime.fromisoformat(value)
        if timezone.is_naive(dt):
            dt = timezone.make_aware(dt)
        return dt
    except (ValueError, TypeError):
        return None


def backfill_source_configurations(apps, schema_editor):
    Study = apps.get_model('studies', 'Study')
    StudySourceConfiguration = apps.get_model('studies', 'StudySourceConfiguration')

    for study in Study.objects.exclude(source_configurations={}):
        configs = study.source_configurations
        if not isinstance(configs, dict):
            continue
        for source_type, config in configs.items():
            if not isinstance(config, dict):
                continue
            requested = config.get('requested_data_types', [])
            if isinstance(requested, list):
                requested = ','.join(requested)
            StudySourceConfiguration.objects.update_or_create(
                study=study,
                source_type=source_type,
                defaults=dict(
                    status=config.get('status', 'optional'),
                    requested_data_types=requested or '',
                    data_start=_parse_dt(config.get('data_start')),
                    data_end=_parse_dt(config.get('data_end')),
                    config_file=config.get('config_file', ''),
                ),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0026_add_studysourceconfiguration_fields'),
    ]

    operations = [
        migrations.RunPython(
            backfill_source_configurations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
