# Generated by Django 5.2 on 2026-05-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0027_backfill_studysourceconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='source_configurations',
        ),
    ]
