# Generated by Django 5.2 on 2026-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0028_remove_source_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysourceconfiguration',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Source configuration. Specific to the source type.'),
        ),
    ]
