# Generated by Django 5.2 on 2026-05-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0029_studysourceconfiguration_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysourceconfiguration',
            name='config_file',
        ),
    ]
