# Generated by Django 5.2 on 2026-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0030_remove_studysourceconfiguration_config_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_page_html',
            field=models.TextField(blank=True, default='', help_text='Front page HTML content.'),
        ),
    ]
