# Generated by Django 5.2 on 2026-06-02 09:19

import django.db.models.deletion
from django.db import migrations, models


LEGACY_CONSENT_SOURCE_MAP = {
    'AwareDataSource': 'aware',
    'JsonUrlDataSource': 'json_url',
    'SurveyDataSource': 'survey',
    'NiimportDataSource': 'niimport',
    'GooglePortabilityDataSource': 'niimport',
    'TikTokPortabilityDataSource': 'niimport',
    'TikTokExportDataSource': 'niimport',
}


def forwards(apps, schema_editor):
    Consent = apps.get_model('studies', 'Consent')
    StudySourceConfiguration = apps.get_model('studies', 'StudySourceConfiguration')
    NiimportDataSource = apps.get_model('data_sources', 'NiimportDataSource')

    for consent in Consent.objects.select_related('study').all():
        if consent.source_configuration_id:
            continue

        source_type = LEGACY_CONSENT_SOURCE_MAP.get(consent.source_type, consent.source_type)
        candidates = list(
            StudySourceConfiguration.objects.filter(
                study_id=consent.study_id,
                source_type=source_type,
            ).order_by('id')
        )
        if not candidates:
            continue

        chosen = None
        if source_type == 'niimport' and consent.data_source_id:
            try:
                niimport_source = NiimportDataSource.objects.get(pk=consent.data_source_id)
                for candidate in candidates:
                    if candidate.configuration.get('niimport_source_type') == niimport_source.niimport_source_type:
                        chosen = candidate
                        break
            except NiimportDataSource.DoesNotExist:
                pass

        consent.source_configuration = chosen or candidates[0]
        consent.save(update_fields=['source_configuration'])


def backwards(apps, schema_editor):
    Consent = apps.get_model('studies', 'Consent')
    Consent.objects.update(source_configuration=None)


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0032_rename_source_type_to_source_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='source_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='studies.studysourceconfiguration'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
