# Generated by Django 5.2 on 2026-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0035_normalize_consent_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysourceconfiguration',
            name='consent_template_html',
            field=models.TextField(blank=True, default='', help_text='Consent text shown to the participant for this source. Overrides the repo-fetched consent_<source_type>.html when set.'),
        ),
    ]
