# Generated by Django 5.2 on 2026-06-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0036_studysourceconfiguration_consent_template_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Asset filename (e.g., 'study_logo.png'). Use this name to reference the asset in your study HTML.", max_length=255)),
                ('file', models.FileField(help_text='Upload the asset file. Images, PDFs, etc.', upload_to='study_assets/')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studies.study')),
            ],
            options={
                'verbose_name': 'Study Asset',
                'verbose_name_plural': 'Study Assets',
                'unique_together': {('study', 'name')},
            },
        ),
    ]
