# Generated by Django 5.2.15 on 2026-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0037_studyasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='join_confirmation_html',
            field=models.TextField(blank=True, default='', help_text='HTML shown on the study-wide confirmation page when a participant clicks Join, before any participation is created.'),
        ),
        migrations.AddField(
            model_name='study',
            name='privacy_notice_html',
            field=models.TextField(blank=True, default='', help_text='Privacy notice HTML content. Shown on the privacy notice page when set.'),
        ),
        migrations.AddField(
            model_name='study',
            name='terms_of_service_html',
            field=models.TextField(blank=True, default='', help_text='Terms of service HTML content. Shown on the terms of service page when set.'),
        ),
    ]
