# Generated by Django 5.2.15 on 2026-07-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0040_migrate_legal_text_to_versioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='privacy_notice_html',
        ),
        migrations.RemoveField(
            model_name='study',
            name='terms_of_service_html',
        ),
    ]
