# Generated by Django 5.2.15 on 2026-07-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0041_remove_study_privacy_notice_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='registration_pending_html',
            field=models.TextField(blank=True, default='', help_text='HTML shown to a participant after they register, while awaiting researcher approval. Typically explains that their registration has been noted and researchers will contact them by email.'),
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='researcher_approved',
            field=models.BooleanField(default=False, help_text='A researcher has approved this participant. Until approved, the participant cannot consent or collect data.'),
        ),
    ]
