# Generated by Django 5.2.15 on 2026-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0042_study_registration_pending_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='collect_tax_id',
            field=models.BooleanField(default=False, help_text='Whether participants should be asked to provide a tax ID'),
        ),
    ]
