# Generated by Django 5.2.15 on 2026-07-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0043_study_collect_tax_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'study', 'verbose_name_plural': 'study'},
        ),
    ]
