# Generated by Django 5.2.15 on 2026-07-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0044_alter_study_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='allowed_email_domains',
            field=models.TextField(blank=True, default='', help_text="Restrict participant email addresses to these domains. Separate multiple domains with commas, spaces, or newlines (e.g. 'example.edu, example.org'). Leave empty to allow any email address."),
        ),
        migrations.AddField(
            model_name='study',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants that can register for the study. Leave empty for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Participants must be approved by a researcher before they can consent or collect data. When off, participants proceed directly after registering (approval is never granted automatically).'),
        ),
    ]
