# Generated by Django 5.2.15 on 2026-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0045_study_allowed_email_domains_study_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='custom_css',
            field=models.FileField(blank=True, help_text='Optional CSS file applied on all pages (mainly the dashboard).', null=True, upload_to='study_assets/'),
        ),
    ]
