# Generated by Django 5.2.15 on 2026-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0046_study_custom_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS applied on all pages (mainly the dashboard).'),
        ),
    ]
